# List methods
l1=["one","Two","Three","One"]
l2=[1,2,3,4,5,3]
print("l1=",l1,"\nl2=",l2)
a=l1.copy()
print("Copying l1 to a : a=",a)
l1.append("Four")
print("Appending four to l1 :",l1)
b=l2.count(3)
print("Count of 3 in l2 :",b)
c=l2.index(2)
print("index of 2 in l2 :",c)
l2.insert(5,6)
print("Inserting 6 in 5th postion :",l2)
l2.pop(6)
print("Popping out a element in 6th postion :",l2)
l1.remove("One")
print("Removing one from l1 :",l1)
l2.reverse()
print("Reversing l2 :",l2)
l2.sort()
print("Sorting l2 :",l2)
l1.extend(l2)
print("Adding l2 to l1 :",l1)
l1.clear()
l2.clear()
print("After clearing both l1 and l2 :",l1,l2)
